#ifndef __CONSTANTS__
#define __CONSTANTS__

enum AGENT_TYPE{
  TYPE_IDLE,
  TYPE_WALKER,
  TYPE_FOLLOWING,
  TYPE_RANDOM_MOVEMENT,
  TYPE_PATH_PATROL,
  TYPE_PATTERN,
  TYPE_CHASER,  
  TYPE_AGENT_COMMANDOS
};

enum AGENT_PATTERNS{
  PATTERN_UP,
  PATTERN_LEFT,
  PATTERN_RIGHT,
  PATTERN_DOWN
};

#endif // !__CONSTANTS__