#ifndef __CONSTANTS__
#define __CONSTANTS__

enum AGENT_TYPE{
  TYPE_IDLE,
  TYPE_WALKER,          // NOT IMPLEMENTED,
  TYPE_FOLLOWING,
  TYPE_RANDOM_MOVEMENT,
  TYPE_PATH_PATROL,
  TYPE_CHASER,  
  TYPE_RUNNER_AWAY,     // NOT IMPLEMENTED
  TYPE_AGENT_COMMANDOS
};

#endif // !__CONSTANTS__